name: git commit skipper
description: Cancels the build if the commit is already built on other branches for a given pipeline
author: "https://github.com/buildkite"
requirements: []
configuration:
  properties:
    read_build_token_env:
      type: string
      description: "Name of the buildkite api token set in your environment to read the build"
  additionalProperties: false

