#!/bin/bash
set -euo pipefail

echo "🔍 Checking  existing builds for commit $BUILDKITE_COMMIT..."

url="https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds?commit=${BUILDKITE_COMMIT}"

echo "URL: $url"

token_var="${BUILDKITE_PLUGIN_SKIP_BUILD_FOR_COMMIT_READ_BUILD_TOKEN_ENV:-}"

if [[ -z "${!token_var:-}" ]] ; then
    echo "+++ 🚨 No read build api token found in \$${token_var} so commit will not be checked"
else

    response=$(curl -s -D - -H "Authorization: Bearer ${!token_var:-}" "$url")

    if $response | grep -q " 404 Not Found"; then
        echo "🚨 404 Not Found: The requested resource could not be found."
        
    else

        body=$(echo "$response" | sed '1,/^\r$/d')

        build_numbers=$(echo "$body" | grep -o '"number":[0-9]\+' | grep -o '[0-9]\+' | sed 's/^0*//')
        duplicate_found=false
        for number in $build_numbers; do
            if [ "$number" != "$BUILDKITE_BUILD_NUMBER" ]; then
                duplicate_found=true
                echo "✅ Commit $BUILDKITE_COMMIT has already been built in build #$number. Skipping step..."
                buildkite-agent annotate "Commit $BUILDKITE_COMMIT has already been built in build #$number. Cancelling the build..." --style "info"
                curl -s -D -H "Authorization: Bearer ${!token_var:-}" \
                        -X PUT "https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds/$BUILDKITE_BUILD_NUMBER/cancel"
                exit 0
            fi
        done
        if ! $duplicate_found; then
            echo "✅ No duplicate build found for commit $BUILDKITE_COMMIT"
        fi
    fi

fi
