#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

echo "🔍 Checking  existing builds for commit $BUILDKITE_COMMIT..."

url="https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds?commit=${BUILDKITE_COMMIT}"

echo "URL: $url"

# Check if the API token is set
API_TOKEN="$(plugin_read_config buildkite_api_token "none")"
if $API_TOKEN == "none"; then
    echo "API token not set. Please set the buildkite_api_token in the plugin configuration."
    exit 1
fi

while [ -n "$url" ]; do
    response=$(curl -s -D - -H "Authorization: Bearer ${API_TOKEN}" "$url")

    body=$(echo "$response" | sed '1,/^\r$/d')

    build_numbers=$(echo "$body" | grep -o '"number":[0-9]\+' | grep -o '[0-9]\+' | sed 's/^0*//')

    for number in $build_numbers; do
        if [ "$number" != "$BUILDKITE_BUILD_NUMBER" ]; then
            echo "✅ Commit $BUILDKITE_COMMIT has already been built in build #$number. Skipping step..."
            buildkite-agent annotate "Commit $BUILDKITE_COMMIT has already been built in build #$number. Cancelling the build..." --style "info"
            curl -H "Authorization: Bearer $API_TOKEN" \
                 -X PUT "https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds/$BUILDKITE_BUILD_NUMBER/cancel"
            exit 0
        fi
    done
done
